import {chromium} from 'file:///C:/Users/banana-10700K-32G/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import {mkdir,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
await mkdir('qa',{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const context=await browser.newContext({viewport:{width:2048,height:977},permissions:['clipboard-read','clipboard-write']});
const page=await context.newPage(),errors=[],results=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.waitForSelector('canvas');
await page.waitForTimeout(1200);
assert.equal(await page.title(),'포인큐브 — 모듈러 3D 컨피규레이터');
assert.doesNotMatch(await page.locator('body').innerText(),/PLANFURNI|플랜퍼니|PLAN FURNI/i);
const brandColors=await page.evaluate(()=>({background:getComputedStyle(document.querySelector('section[aria-label="3D 보기"]>div')).backgroundColor,notice:getComputedStyle(document.querySelector('.ticker')).backgroundColor,button:getComputedStyle(document.querySelector('.btn-store')).backgroundColor}));
assert.deepEqual(brandColors,{background:'rgb(235, 235, 235)',notice:'rgb(255, 216, 0)',button:'rgb(77, 96, 128)'});
for(const option of await page.getByRole('listbox',{name:'레퍼런스 구성',exact:true}).getByRole('option').all()){
 await option.click();
 const links=await page.locator('a[href]').evaluateAll(aa=>aa.map(a=>a.getAttribute('href')));
 assert(links.every(href=>href==='https://smartstore.naver.com/4incube'||href==='http://pf.kakao.com/_xndWBX'));
}
await page.getByRole('option',{name:/^No\.2 1523/}).click();
for(const [width,height] of [[2535,1209],[2048,977],[1440,900],[1024,768],[768,1024],[390,844],[360,800]]){
 await page.setViewportSize({width,height});
 await page.waitForTimeout(700);
 const metrics=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,canvas:!!document.querySelector('canvas'),brokenImages:[...document.images].filter(i=>i.complete&&!i.naturalWidth).length,summary:document.querySelector('aside[aria-label="요약"]').getBoundingClientRect().toJSON()}));
 await page.screenshot({path:`qa/screen-${width}.png`,fullPage:width<1024});
 results.push({width,height,...metrics});
}
await page.setViewportSize({width:1440,height:900});
await page.getByRole('option',{name:/^No\.1 773/}).click();
assert.match(await page.locator('header').innerText(),/No\.1/);
await page.getByRole('button',{name:'되돌리기',exact:true}).click();
assert.match(await page.locator('header').innerText(),/1523 × 373 × 740/);
await page.getByRole('button',{name:'다시 실행',exact:true}).click();
assert.match(await page.locator('header').innerText(),/773 × 373 × 740/);
await page.getByRole('option',{name:/^No\.2 1523/}).click();
await page.getByRole('button',{name:'가로 칸 수 늘리기',exact:true}).click();
assert.match(await page.getByLabel('요약',{exact:true}).innerText(),/가로 3칸/);
await page.getByRole('button',{name:'되돌리기',exact:true}).click();
await page.getByRole('radio',{name:'오렌지',exact:true}).click();
await page.getByRole('gridcell',{name:'1열 2단: 도어',exact:true}).click();
await page.getByRole('radiogroup',{name:'칸 타입',exact:true}).getByRole('radio',{name:'오픈',exact:true}).click();
assert.equal(await page.getByRole('gridcell',{name:'1열 2단: 오픈',exact:true}).count(),1);
await page.getByRole('button',{name:'좌우 반전',exact:true}).click();
assert.equal(await page.getByRole('gridcell',{name:'2열 2단: 오픈',exact:true}).count(),1);
await page.getByRole('button',{name:'공유 링크 복사',exact:true}).click();
const share=await page.evaluate(()=>navigator.clipboard.readText());
assert.match(share,/127\.0\.0\.1:4173/);
const restored=await context.newPage();
await restored.goto(share,{waitUntil:'networkidle'});
assert.equal(await restored.getByRole('gridcell',{name:'2열 2단: 오픈',exact:true}).count(),1);
await restored.close();
await page.locator('summary').filter({hasText:'자재 목록'}).click();
await page.locator('summary').filter({hasText:'가격 상세'}).click();
const downloadPromise=page.waitForEvent('download');
await page.getByRole('button',{name:'이미지 저장',exact:true}).click();
const download=await downloadPromise;
assert.match(download.suggestedFilename(),/^4incube-/);
await download.saveAs('qa/furniture-export.png');
const canvas=page.locator('canvas');
const bounds=await canvas.boundingBox();
await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
await page.mouse.down();await page.mouse.move(bounds.x+bounds.width/2+100,bounds.y+bounds.height/2+40,{steps:10});await page.mouse.up();
await page.mouse.wheel(0,150);
await page.screenshot({path:'qa/interactions.png'});
await page.setViewportSize({width:390,height:844});
await page.getByRole('tab',{name:'컬러',exact:true}).click();
await page.getByRole('radio',{name:'스틸블루',exact:true}).click();
await page.getByRole('tab',{name:'요약',exact:true}).click();
assert.equal(await page.getByLabel('요약',{exact:true}).isVisible(),true);
await page.screenshot({path:'qa/mobile-summary.png',fullPage:true});
const report={results,errors,features:['preset','undo','redo','column count','color','cell type','mirror','share roundtrip','BOM','price details','image export','rotate/zoom','mobile tabs'],share};
await writeFile('qa/report.json',JSON.stringify(report,null,2));
console.log(JSON.stringify(report,null,2));
await browser.close();
